import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, rm, writeFile, access } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import type { AddressInfo } from 'node:net';
import type { StoredJob, StoredSource } from '../server/store.js';
import type { ExportHistoryEntry } from '../shared/types.js';
import { DEFAULT_SETTINGS } from '../shared/types.js';
import { failWorkspaceWrites } from './helpers/workspace.js';

test('drafts, reconnecting originals, review queue, projects and retention persist together', { timeout: 30000 }, async () => {
  const dir = await mkdtemp(path.join(tmpdir(), 'remix-workspace-features-'));
  process.env.DATA_DIR = dir;
  const { initStore, state, saveStore, closeStore, publicJob, publicSource } = await import('../server/store.js');
  const { config, paths } = await import('../server/config.js');
  const { createApp } = await import('../server/app.js');
  const { cleanupExpired } = await import('../server/queue.js');
  await initStore();
  const old = new Date(Date.now() - config.retentionMs - 60000).toISOString();
  const source: StoredSource = { id: 'original', name: 'Original', filePath: path.join(paths.uploads, 'original.mp4'), thumbnailPath: path.join(paths.thumbnails, 'original.jpg'), thumbnailUrl: '', duration: 10, width: 160, height: 90, fps: 24, hasAudio: false, size: 4, createdAt: old, fingerprint: 'same-hash' };
  const job: StoredJob = { id: 'edit', sourceId: source.id, sourceName: source.name, batchId: 'collection', variant: 1, status: 'completed', progress: 100, createdAt: old, finishedAt: old, outputPath: path.join(paths.outputs, 'edit.mp4'), settings: { ...DEFAULT_SETTINGS },
    editPlan: { version: 1, revision: 1, sourceId: source.id, sourceDuration: 10, outputDuration: 10, createdAt: old, settings: { ...DEFAULT_SETTINGS }, cuts: [{ start: 0, end: 10 }], captions: [], visuals: [], narration: false, media: [] } };
  const history: ExportHistoryEntry = { id: job.id, jobId: job.id, sourceId: source.id, sourceFingerprint: source.fingerprint!, sourceName: source.name, title: 'Original edit', createdAt: old, revision: 1, cuts: [{start:0,end:10}], stockShots: [], publications: [], sourceText: '', outputDuration: 10 };
  await Promise.all([writeFile(source.filePath, 'test'), writeFile(source.thumbnailPath, 'test'), writeFile(job.outputPath, 'output-file')]);
  state.sources.push(source); state.jobs.push(job); await saveStore([history]);
  const server = createApp().listen(0, '127.0.0.1');
  await new Promise<void>(resolve => server.once('listening', resolve));
  const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const request = (url: string, method = 'GET', body?: unknown, headers: Record<string,string> = {}) => fetch(base + url, { method, headers: { 'Content-Type':'application/json', ...headers }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const content = JSON.stringify({ draft: { ...job.editPlan, captions: [{ id: 'caption', start: 0, end: 1, text: 'Corrected' }] }, refreshBroll: false, brollCount: 3, brollMaxCoverage: 50, promptAnchor: null, reviewTime: 2 });
  try {
    assert.equal((await (await request('/api/jobs/edit/source-status')).json()).available, true);
    assert.equal((await (await request('/api/jobs/edit/draft')).json()).draft, null);
    assert.equal((await request('/api/jobs/edit/draft', 'PUT', { revision:1,content:'broken',token:null })).status, 400);
    const saved = await request('/api/jobs/edit/draft', 'PUT', { revision:1,content,token:null });
    assert.equal(saved.status, 200); const first = (await saved.json()).draft;
    assert.equal((await request('/api/jobs/edit/draft','PUT',{revision:1,content,token:null})).status,409);
    assert.equal((await request('/api/jobs/edit/draft','PUT',{revision:2,content,token:first.token})).status,409);
    assert.equal((await request('/api/jobs/edit/draft','DELETE')).status,409);
    await failWorkspaceWrites(dir, true);
    assert.equal((await request('/api/jobs/edit/draft','DELETE',undefined,{'If-Match':first.token})).status,500);
    assert.equal(job.editorDraft?.token,first.token);
    await failWorkspaceWrites(dir, false);
    assert.equal(publicJob(job).expiresAt,undefined); assert.ok(publicJob(job).draftSavedAt);
    assert.equal((await request('/api/sources/original','DELETE')).status,409);
    assert.deepEqual((await (await request('/api/batches/collection','DELETE')).json()).removedIds,[]);
    await cleanupExpired(); await access(job.outputPath); await access(source.filePath);
    closeStore(); await initStore(); await cleanupExpired();
    assert.equal(state.jobs[0].editorDraft?.content,content,'draft and file protection survive restart');

    await rm(source.filePath);
    const missing = await (await request('/api/jobs/edit/source-status')).json();
    assert.equal(missing.available,false); assert.equal(missing.canMatch,true);
    const wrong = { ...source, id:'wrong', fingerprint:'wrong-hash', filePath:path.join(paths.uploads,'wrong.mp4') };
    const matching = { ...source, id:'matching', filePath:path.join(paths.uploads,'matching.mp4') };
    await Promise.all([writeFile(wrong.filePath,'wrong'),writeFile(matching.filePath,'test')]); state.sources.push(wrong, matching); await saveStore();
    assert.equal((await request('/api/jobs/edit/reconnect','POST',{sourceId:'wrong'})).status,409);
    const candidates = await (await request('/api/jobs/edit/source-status')).json();
    assert.deepEqual(candidates.candidates.map((item: {id:string})=>item.id),['matching']);
    assert.equal((await request('/api/jobs/edit/reconnect','POST',{sourceId:'matching'})).status,200);
    assert.equal(state.jobs[0].sourceId,'matching');
    const reconnected = (await (await request('/api/jobs/edit/draft')).json()).draft;
    assert.equal(JSON.parse(reconnected.content).draft.sourceId,'matching');
    assert.notEqual(reconnected.token,first.token);
    assert.equal((await (await request('/api/jobs/edit/source-status')).json()).available,true);

    assert.equal((await request('/api/sources/matching/project','PATCH',{project:'Launch'})).status,200);
    assert.equal(publicJob(state.jobs[0]).project,'Launch');
    assert.equal((await request('/api/history/edit/project','PATCH',{project:'Archive'})).status,200);
    assert.deepEqual((await (await request('/api/library/projects')).json()).projects,['Archive','Launch']);
    assert.equal((await (await request('/api/history?project=Archive&limit=1')).json()).total,1);
    assert.equal((await request('/api/history?review=invalid')).status,400);
    assert.equal((await request('/api/history?after=2026-10-05&before=2026-09-01')).status,400);
    assert.equal((await request('/api/jobs/edit/review','PATCH',{verdict:'needs-edit',notes:'Fix framing'})).status,200);
    assert.equal(publicJob(state.jobs[0]).review?.verdict,'needs-edit');
    assert.equal((await (await request('/api/history?review=needs-edit')).json()).total,1);
    assert.equal((await request('/api/exports/accepted.zip?ids=edit')).status,404);
    await request('/api/jobs/edit/review','PATCH',{verdict:'accepted-after-correction'});
    const zip = await request('/api/exports/accepted.zip?ids=edit');
    assert.equal(zip.status,200); assert.equal(Buffer.from(await zip.arrayBuffer()).subarray(0,2).toString(),'PK');
    await request('/api/jobs/edit/review','PATCH',{verdict:null});
    assert.equal(publicJob(state.jobs[0]).review?.verdict,undefined);
    assert.equal(publicJob(state.jobs[0]).review?.notes,'Fix framing');

    const owner = '9dde3e2c-980c-4f38-b2cc-d993361fb974', otherOwner = '9dde3e2c-980c-4f38-b2cc-d993361fb975';
    await request(`/api/draft-sources/${owner}`,'PUT',{sourceIds:['wrong']});
    await request(`/api/draft-sources/${otherOwner}`,'PUT',{sourceIds:['wrong']});
    await request(`/api/draft-sources/${owner}`,'PUT',{sourceIds:[]});
    assert.equal(publicSource(state.sources.find(item=>item.id==='wrong')!).draftProtected,true);
    await cleanupExpired(); assert.ok(state.sources.some(item=>item.id==='wrong'));
    assert.equal((await request('/api/sources/wrong','DELETE')).status,409);
    assert.equal((await request('/api/sources/wrong/draft-protection','DELETE',{})).status,400);
    assert.equal((await request('/api/sources/wrong/draft-protection','DELETE',{release:true})).status,200);
    await cleanupExpired(); assert.ok(!state.sources.some(item=>item.id==='wrong'));
    assert.equal((await request('/api/batches/collection/keep','PATCH')).status,200);
    assert.ok(state.jobs[0].keptAt);
    const cleared = await request('/api/jobs/edit/draft','DELETE',undefined,{'If-Match':reconnected.token});
    assert.equal(cleared.status,200); assert.equal(state.jobs[0].editorDraft,undefined);
    assert.ok(Date.now()-Date.parse(state.jobs[0].retentionResetAt!)<5000);
    await request('/api/jobs/edit/keep','PATCH',{keep:false}); await cleanupExpired(); await access(job.outputPath);
  } finally { await new Promise<void>(resolve=>server.close(()=>resolve())); closeStore(); await rm(dir,{recursive:true,force:true}); }
});
