"""Local LaMa patch renderer. One frame in memory, <=512px model input, no network.

Plans are generated by the server, never accepted directly from HTTP clients.
The pinned TorchScript model comes from the Apache-2.0 LaMa project; see models/.
"""
import argparse
import gc
import hashlib
import json
import math
import os
from pathlib import Path
import signal
import subprocess
import sys
import tempfile

ROOT = Path(__file__).resolve().parent


def verified_model():
    manifest = json.loads((ROOT / "lama-model.json").read_text())
    model = ROOT / "models" / manifest["filename"]
    digest = hashlib.sha256()
    with model.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    if digest.hexdigest() != manifest["sha256"]:
        raise RuntimeError("LaMa model integrity check failed. Run npm run setup:watermark again.")
    return model


def read_frame(stream, size):
    data = bytearray()
    while len(data) < size:
        chunk = stream.read(size - len(data))
        if not chunk:
            if data:
                raise RuntimeError("Incomplete source frame during watermark reconstruction.")
            return None
        data.extend(chunk)
    return data


def stop(child):
    if child is None:
        return
    if child.poll() is None:
        child.terminate()
        try:
            child.wait(timeout=.3)
        except subprocess.TimeoutExpired:
            child.kill()
    child.wait()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--plan")
    args = parser.parse_args()
    # Imports remain inside main so frame IO helpers can be tested without ML installed.
    import cv2
    import numpy as np
    import torch

    torch.set_num_threads(min(6, os.cpu_count() or 1))
    cv2.setNumThreads(1)
    torch.manual_seed(0)
    model = verified_model()
    device = "mps" if torch.backends.mps.is_available() else "cpu"
    if args.check:
        print(json.dumps({"available": True, "device": device}), flush=True)
        return
    plan = json.loads(Path(args.plan).read_text())
    net = torch.jit.load(str(model), map_location=device).eval()
    fps = plan["fps"]
    expected = max(1, math.ceil(plan["duration"] * fps))
    common = ["ffmpeg", "-hide_banner", "-loglevel", "error", "-nostdin", "-y", "-threads", "2"]
    for index, area in enumerate(plan["areas"]):
        crop, box = area["crop"], area["box"]
        cw, ch, bw, bh = crop["width"], crop["height"], box["width"], box["height"]
        bx, by = box["x"] - crop["x"], box["y"] - crop["y"]
        alpha = cv2.imread(area["alpha"], cv2.IMREAD_GRAYSCALE)
        if alpha is None or alpha.shape != (bh, bw):
            raise RuntimeError("Invalid watermark mask file.")
        mask = np.zeros((ch, cw), dtype=np.uint8)
        mask[by:by + bh, bx:bx + bw] = np.where(alpha > 0, 255, 0)
        scale = min(1, 512 / max(cw, ch))
        tw, th = max(1, round(cw * scale)), max(1, round(ch * scale))
        pw, ph = (-tw) % 8, (-th) % 8
        # Area resampling retains thin strokes; pad rather than stretch the picture.
        small_mask = (cv2.resize(mask, (tw, th), interpolation=cv2.INTER_AREA) > 0).astype(np.float32)
        small_mask = np.pad(small_mask, ((0, ph), (0, pw)), mode="edge")
        mt = torch.from_numpy(small_mask[None, None]).to(device)
        decode = common + plan["inputArgs"] + ["-map", "0:V:0", "-an", "-sn", "-dn", "-vf",
            ",".join(plan["filters"] + ["format=rgb24", f"crop={cw}:{ch}:{crop['x']}:{crop['y']}:exact=1"]),
            "-t", str(plan["duration"]), "-threads", "1", "-pix_fmt", "rgb24", "-f", "rawvideo", "pipe:1"]
        encode = common + ["-f", "rawvideo", "-pix_fmt", "rgb24", "-s", f"{bw}x{bh}", "-r", str(fps),
            "-i", "pipe:0", "-an", "-c:v", "ffv1", "-level", "3", "-threads", "1", "-pix_fmt", "bgr0", area["output"]]
        decoder = encoder = None
        # Files avoid stderr pipe deadlocks; no frame arrays or unbounded logs in RAM.
        with tempfile.TemporaryFile() as decode_log, tempfile.TemporaryFile() as encode_log:
            try:
                decoder = subprocess.Popen(decode, stdout=subprocess.PIPE, stderr=decode_log, stdin=subprocess.DEVNULL)
                encoder = subprocess.Popen(encode, stdin=subprocess.PIPE, stderr=encode_log, stdout=subprocess.DEVNULL)
                count = 0
                while True:
                    raw = read_frame(decoder.stdout, cw * ch * 3)
                    if raw is None:
                        break
                    at = count / fps
                    active = not area["intervals"] or any(i["start"] <= at < i["end"] for i in area["intervals"])
                    if active:
                        frame = np.frombuffer(raw, dtype=np.uint8).reshape(ch, cw, 3)
                        small = cv2.resize(frame, (tw, th), interpolation=cv2.INTER_AREA)
                        small = np.pad(small, ((0, ph), (0, pw), (0, 0)), mode="symmetric")
                        it = torch.from_numpy(small.transpose(2, 0, 1).copy()).float()[None].to(device) / 255
                        try:
                            with torch.inference_mode():
                                prediction = net(it, mt)[0].permute(1, 2, 0).cpu().numpy()
                        except (RuntimeError, NotImplementedError):
                            if device != "mps":
                                raise
                            # Some older Apple/PyTorch versions lack FFT support on Metal.
                            # Retry the same frame on CPU; never substitute a blurry fill.
                            device = "cpu"
                            del net
                            it, mt = it.cpu(), mt.cpu()
                            gc.collect()
                            torch.mps.empty_cache()
                            net = torch.jit.load(str(model), map_location="cpu").eval()
                            with torch.inference_mode():
                                prediction = net(it, mt)[0].permute(1, 2, 0).numpy()
                        if not np.isfinite(prediction).all():
                            raise RuntimeError("LaMa returned an invalid frame.")
                        restored = cv2.resize(np.clip(prediction[:th, :tw] * 255, 0, 255), (cw, ch), interpolation=cv2.INTER_LINEAR)
                        patch = restored[by:by + bh, bx:bx + bw].astype(np.uint8)
                    else:
                        patch = np.zeros((bh, bw, 3), dtype=np.uint8)
                    encoder.stdin.write(patch.tobytes())
                    count += 1
                    if count == 1 or count % max(1, round(fps / 2)) == 0:
                        print(json.dumps({"progress": min(99, 100 * (index + min(1, count / expected)) / len(plan["areas"])), "device": device}), flush=True)
                encoder.stdin.close()
                if decoder.wait() != 0 or encoder.wait() != 0 or count == 0:
                    raise RuntimeError("Could not read or write the watermark video patch.")
            except Exception as error:
                for log in (decode_log, encode_log):
                    log.seek(max(0, log.seek(0, 2) - 1500))
                    sys.stderr.write(log.read().decode(errors="replace"))
                raise error
            finally:
                stop(decoder)
                stop(encoder)
        del mt
    print(json.dumps({"progress": 100, "device": device}), flush=True)


if __name__ == "__main__":
    signal.signal(signal.SIGTERM, lambda *_: sys.exit(130))
    try:
        main()
    except Exception as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
