export const ONBOARDING_SESSION_KEY = "remix-onboarding-session-v1";
type SessionStorage = Pick<Storage, "getItem" | "setItem">;
export function shouldShowOnboarding(storage?: SessionStorage) {
  try { return (storage ?? window.sessionStorage).getItem(ONBOARDING_SESSION_KEY) !== "seen"; }
  catch { return true; }
}
export function rememberOnboarding(storage?: SessionStorage) {
  try { (storage ?? window.sessionStorage).setItem(ONBOARDING_SESSION_KEY, "seen"); }
  catch { /* The tour still works when browser storage is unavailable. */ }
}

export type TourDestination = {
  view: "studio" | "exports" | "history";
  mode?: "auto" | "manual" | "shorts";
  tab?: "essentials" | "color" | "advanced" | "all";
};
export interface TourStep {
  id: string;
  chapter: string;
  title: string;
  description: string;
  options: readonly (readonly [string, string])[];
  target?: string;
  destination?: TourDestination;
  reveal?: string;
}
const auto = { view: "studio", mode: "auto" } as const;
const manual = (tab: TourDestination["tab"]): TourDestination => ({ view: "studio", mode: "manual", tab });

export const TOUR_STEPS: readonly TourStep[] = [
  { id: "welcome", chapter: "Welcome", title: "Find your way around Remix Studio",
    description: "Follow the highlights to learn the editing options. You can explore the whole tour or jump straight to a topic.",
    options: [["Import → edit → export", "Bring a video, choose how to edit it, then review your finished cut."],
      ["Go at your own pace", "Use Next, Back or Jump to topic. No video is needed to follow along."],
      ["Leave whenever you like", "Skip, ×, Escape or a click outside closes the tour. Open Quick guide to replay it."]],
  },
  { id: "imports", chapter: "Your footage", title: "Bring in your videos", target: ".import-panel .dropzone", destination: auto,
    description: "Every imported video joins the same workspace for Auto, Manual and Short clips.",
    options: [["Browse or drop files", "Import one video or a batch. The uploader shows your current file and batch limits."],
      ["Pause and resume", "Large files upload in chunks. After reloading, select the same unchanged file to resume."],
      ["Import status", "Follow upload and preparation progress. Cancel unfinished imports or dismiss completed cards."]],
  },
  { id: "links", chapter: "Your footage", title: "Import several video links at once", target: ".import-social", destination: auto,
    description: "Paste TikTok, Instagram and YouTube links together in Import video links. Separate them with new lines, spaces or commas, then import the batch.",
    options: [["Check your batch", "The button shows how many videos will import. Duplicates are skipped; invalid entries stay in the field for correction while valid links can continue."],
      ["Download in the background", "Each video has its own progress with your other imports. Downloads continue while the app server is running."],
      ["If a link cannot download", "A private, unavailable or blocked video may need a local copy. Use Browse files to import it."]],
  },
  { id: "local-files", chapter: "Your footage", title: "Use large originals without copying", target: ".import-link-button", destination: auto,
    description: "Link files on this computer lets you paste full paths to videos stored on the machine running the app.",
    options: [["One path per line", "On Mac, select files in Finder and press Option + Command + C to copy their paths."],
      ["Keep originals in place", "Linked files must stay at the same path and remain unchanged until your exports finish."]],
  },
  { id: "modes", chapter: "Editing modes", title: "Choose how you want to edit", target: ".mode-switch", destination: auto,
    description: "Switch modes at the top of the workspace. Each gives you a different amount of control.",
    options: [["Auto remix", "Choose your preferences; Auto selects an excerpt and prepares the edit."],
      ["Manual", "Set the trim, picture, audio and text yourself. Manual settings stay separate from Auto."],
      ["Short clips", "Build named shorts from exact timestamps, including multiple sequences from a long recording."]],
  },
  { id: "auto-scope", chapter: "Auto", title: "Choose which video you are changing", target: ".auto-scope", destination: auto,
    description: "Select a source card or use Editing preferences for to change that video's Auto settings.",
    options: [["Per-video preferences", "Format, length, text, sound, visuals and version count belong to the selected source."],
      ["Use for all videos", "With multiple sources, copy these preferences to the other videos and future imports."],
      ["Starting preferences", "Before importing, your choices become the defaults for new videos."]],
  },
  { id: "black-bands", chapter: "Auto", title: "Frame your video with black bands", target: ".auto-layout", destination: auto,
    description: "Choose the output Format, then enable Black bands to make room for persistent captions above and below your picture.",
    options: [["Format and fit", "Choose portrait, square, 4:5, landscape or original. Keep the whole picture preserves the source; Fill the window crops its edges."],
      ["Top and bottom bands", "Adjust their heights separately. A portrait source stays fully visible with side space when you keep the whole picture."],
      ["Band text", "Write a headline above and an optional caption below. Adjust text size; the white text wraps and shrinks to fit."]],
  },
  { id: "footage-presets", chapter: "Auto", title: "Reuse footage and finishing styles", target: ".auto-panel .own-footage", destination: auto, reveal: ".auto-panel .own-footage",
    description: "Add my own footage gives you deliberate clip placements. Finishing presets saves a visual style you want to reuse.",
    options: [["Your footage placements", "Choose uploaded clips and place them before, after or inside the edit using the placement controls."],
      ["Finishing presets", "Save and apply a named finish across editing modes. Band styling is reused while each video's written band text is kept."],
      ["Optional extras", "Leave placements empty to use only the source and whichever supporting visuals you choose."]],
  },
  { id: "pacing", chapter: "Auto", title: "Set the rhythm of the conversation", target: ".auto-panel .pacing-options", destination: auto,
    description: "Pacing decides how much space to keep between spoken phrases.",
    options: [["Original / Natural / Tight", "Keep pauses as recorded, preserve breathing room, or shorten longer pauses."],
      ["Custom", "Set the pause threshold and how much silence to retain."],
      ["Remove isolated fillers", "Optionally remove clear, separately timed “um” and “uh” sounds while keeping meaningful words."]],
  },
  { id: "length-versions", chapter: "Auto", title: "Set length and number of versions", target: '[data-tour="auto-length"]', destination: auto,
    description: "Output preferences controls how much of the source Auto uses and how many different edits it tries to make.",
    options: [["Target length", "Enter a whole number of seconds. It is an upper limit; Auto never extends footage to reach it."],
      ["Maximum versions", "Request 1–10 versions per video. Similar cuts can be skipped, so the finished count may be lower."],
      ["Generate anyway", "A skipped version can be explicitly generated from its export card."]],
  },
  { id: "captions", chapter: "Auto", title: "Choose how speech captions are added", target: '[data-tour="auto-captions"]', destination: auto,
    description: "Speech captions follow spoken words. They are separate from the persistent words in your black bands.",
    options: [["Auto · avoid duplicates", "Check for captions already baked into the footage before adding new text."],
      ["Keep original / Add new", "Keep original adds no speech captions, hooks or callouts. Add new explicitly requests generated captions."],
      ["Caption appearance", "Choose a look, then adjust font, size, color, case, outline, shadow, spacing, alignment, position and background. Leave lower band text empty if captions use that space."]],
  },
  { id: "sound", chapter: "Auto", title: "Keep or reshape the original sound", target: '[data-tour="auto-sound"]', destination: auto,
    description: "Sound controls audio treatment. New narration is a separate choice below the review settings.",
    options: [["None · keep original audio", "Skip sound effects, loudness normalization, cut fades and replacement narration. Audio still follows the video cuts and is re-encoded for export."],
      ["Auto or a sound look", "Auto measures speech and chooses a treatment. Or select Clear voice, Podcast, Warm, Bright, Noisy room, Smooth or Phone call yourself."],
      ["New narration", "When available, replace the voice with a scripted read. None and Keep original captions prevent replacement narration."]],
  },
  { id: "reviews", chapter: "Auto", title: "Choose the automatic review checks", target: '[data-tour="auto-review"]', destination: auto,
    description: "Reviews help find issues with the selected story and the finished video.",
    options: [["Editorial review", "Check the opening, meaning and ending. Choose Check and repair, Check only or Off."],
      ["Review finished picture & sound", "Inspect sampled frames and captions against the soundtrack. This adds processing time."],
      ["Review the findings yourself", "AI checks can miss things. Where enabled, DeepSeek receives the relevant text or sampled images; transcription stays local."]],
  },
  { id: "supporting-visuals", chapter: "Auto", title: "Choose optional supporting visuals", target: ".supporting-visuals", destination: auto,
    description: "Choose any combination, or leave every source off to keep only your original footage.",
    options: [["Pixabay / Pexels", "Add moving stock footage. HyperFrames / Remotion add illustrated explainer cards. My B-roll uses clips from your own library."],
      ["Count and coverage", "When visuals are enabled, set the total shot count and maximum percentage of the result they may cover."],
      ["Matching and library", "Tag your clips or use available AI matching. Stock uses meaning and visual checks. Clips without a suitable match may be skipped; the export explains unfilled requests."]],
  },
  { id: "auto-render", chapter: "Auto", title: "Choose what to render", target: ".auto-render-bar", destination: auto,
    description: "The render bar summarizes the result you are asking for before you start.",
    options: [["This / selected / all videos", "Choose one source, check source cards for a selection, or process the whole workspace."],
      ["Auto remix", "Start the batch when you are ready. Each source uses its own saved preferences."],
      ["Follow Exports", "Watch progress and review the finished versions there. This tour never starts a render."]],
  },
  { id: "manual-frame", chapter: "Manual", title: "Take control of the picture", target: '[data-tour="manual-frame-it-right"]', destination: manual("essentials"),
    description: "Essentials contains Color looks, Frame it right, and Pace & sound. Tabs separate the controls; All controls shows them together.",
    options: [["Frame it right", "Set format and resolution, fill and crop, fit the whole video, or use a blurred background. Black bands and their text are available here too."],
      ["Subject and motion", "Adjust zoom, horizontal or vertical position, mirror, gentle push-in and video cleanup."],
      ["Preview", "Compare the original with your draft. Render a five-second preview to check effects that the live preview only approximates."]],
  },
  { id: "manual-audio", chapter: "Manual", title: "Fine-tune speed and audio", target: '[data-tour="manual-pace-sound"]', destination: manual("essentials"),
    description: "Use the Pace & sound controls to make deliberate changes to the selected video's soundtrack.",
    options: [["Speed, volume and mute", "Change playback speed or volume, or remove sound from the output."],
      ["Loudness and sound modifiers", "Enable normalization, select a sound look, or open the detailed modifiers to adjust the treatment."],
      ["Replacement audio", "Upload another audio track or remove it to return to source audio. Mute takes priority over the track."]],
  },
  { id: "manual-color", chapter: "Manual", title: "Adjust color and texture", target: '[data-tour="manual-light-color"]', destination: manual("color"),
    description: "Color & feel gives you individual picture adjustments, alongside the ready-made Color looks in Essentials.",
    options: [["Light & color", "Adjust brightness, contrast, saturation, temperature, hue shift and gamma."],
      ["Texture", "Control sharpness and film grain. Reset color adjustments if you want to start over."],
      ["Small changes are easy to compare", "Use the original/draft preview switch to judge the result before exporting."]],
  },
  { id: "manual-timing", chapter: "Manual", title: "Choose the timing and opening hook", target: '[data-tour="manual-trim-motion"]', destination: manual("advanced"),
    description: "Advanced contains Trim & motion, Give it a hook, Captions, and Export details.",
    options: [["Trim & motion", "Set start and end, shift the chosen interval, or tune blend and frame blend. Existing multi-cut edits retain their sequences."],
      ["Give it a hook", "Write opening text and set how long it appears."],
      ["Captions", "Keep original captions, import an SRT, or request automatic speech captions with duplicate detection or explicit addition. Customize their appearance below."]],
  },
  { id: "manual-visuals", chapter: "Manual", title: "Add B-roll to your manual edit", target: ".manual-supporting-visuals", destination: manual("essentials"),
    description: "Supporting visuals sit below the editing controls in every Manual tab. Your cuts, speed and audio settings remain yours.",
    options: [["Choose sources", "Mix Pixabay, Pexels, HyperFrames, Remotion and My B-roll, or leave all off for original footage."],
      ["Count, coverage and matching", "Set how many supporting shots to request and how much footage they may cover. Select uploaded clips and match by tags or available AI."],
      ["Check the export", "Supporting shots are assembled during the full export; Live and five-second previews show your manual footage without them."]],
  },
  { id: "manual-finish", chapter: "Manual", title: "Save your finish and render a batch", target: '[data-tour="manual-export-details"]', destination: manual("all"),
    description: "Manual also supports saved presets, changes described in words, and batch exports.",
    options: [["Export details", "Choose source, 24, 30 or 60 fps and whether to clean file metadata."],
      ["Presets and prompt edits", "Save a finishing preset or describe an edit in the prompt editor. Review the proposed changes before applying them."],
      ["Batch controls", "Apply settings to all videos when wanted. Set versions, variation and render scope in the render bar; Reset settings and Surprise me are in the workspace toolbar."]],
  },
  { id: "shorts", chapter: "Short clips", title: "Build shorts from exact moments", target: ".shorts-editor", destination: { view: "studio", mode: "shorts" },
    description: "Create a named short from a source recording. Add sequences, set their in/out times, reorder them or duplicate a short.",
    options: [["Find and frame moments", "Use source playback and the available moment suggestions. Choose frame, quality, crop zoom and subject position; automatic centering can follow a face or speaker."],
      ["Pacing and sound", "Adjust pauses, even out audio or enable gentle cleanup. Preview a sample before committing to a full render."],
      ["Review drafts", "Your shorts are saved in this browser. Review and approve drafts, then render the current, selected, approved or all shorts."]],
  },
  { id: "exports", chapter: "Results", title: "Review and download your exports", target: ".exports-panel", destination: { view: "exports" },
    description: "Exports groups your jobs into batches, with current stages, warnings, errors and completed videos.",
    options: [["Progress and recovery", "Cancel work, retry eligible failures, or read why a version was skipped."],
      ["Preview and download", "Watch the result and read what changed. Download an MP4, available SRT captions, or the completed batch as a ZIP."],
      ["Keep what you need", "Generated files are retained for the period shown in the app. Download them before cleanup; History keeps the editing record."]],
  },
  { id: "revisions", chapter: "Results", title: "Refine a finished result", target: ".exports-panel", destination: { view: "exports" },
    description: "Open Edit this result on an editable export to make a revision without starting the whole edit again.",
    options: [["Cuts, visuals and text", "Refine sequences, replace supporting shots, adjust hooks and captions, and change framing or black-band text."],
      ["Placement guides", "Use the platform interface guide to keep important text away from social-app buttons and post descriptions."],
      ["Review and render", "Inspect flagged moments, retry available reviews, preview changes and render a new revision. These controls appear when an editable result exists."]],
  },
  { id: "history", chapter: "Results", title: "Keep track of what you have made", target: ".history-panel", destination: { view: "history" },
    description: "History keeps export records, source excerpts and previous uses, including revisions.",
    options: [["Search and compare", "Find earlier edits and inspect exact or similar source matches before reusing footage."],
      ["Record publications and feedback", "Save the platform, account and post link, then record review notes and results you actually measured."],
      ["Learn from your edits", "Compare recorded results and download measurements. Recording a publication does not publish a video for you."]],
  },
  { id: "ready", chapter: "Ready", title: "Your next cut starts here", target: ".mode-switch", destination: auto,
    description: "Import a video, choose a mode, then review your settings before rendering.",
    options: [["Come back whenever you need", "Quick guide and How it works reopen this tour. Jump to topic goes straight to a particular option."],
      ["Your work stays yours", "The tour only moves between views. Your settings, footage and exports are unchanged."],
      ["Once per session", "This guide opens automatically once per browser-tab session. Reloading after you finish or dismiss it keeps it closed."]],
  },
];
