export const ONBOARDING_SESSION_KEY = "remix-onboarding-session-v1";
type SessionStorage = Pick<Storage, "getItem" | "setItem">;
export function shouldShowOnboarding(storage?: SessionStorage) {
  try { return (storage ?? window.sessionStorage).getItem(ONBOARDING_SESSION_KEY) !== "seen"; }
  catch { return true; }
}
export function rememberOnboarding(storage?: SessionStorage) {
  try { (storage ?? window.sessionStorage).setItem(ONBOARDING_SESSION_KEY, "seen"); }
  catch { /* The tour still works when browser storage is unavailable. */ }
}

export type TourDestination = {
  view: "studio" | "exports" | "history";
  mode?: "auto" | "manual" | "shorts";
  tab?: "essentials" | "color" | "advanced" | "all";
};
export interface TourStep {
  id: string;
  chapter: string;
  title: string;
  description: string;
  options: readonly (readonly [string, string])[];
  target?: string;
  fallbackTarget?: string;
  destination?: TourDestination;
  reveal?: string;
}
const auto = { view: "studio", mode: "auto" } as const;
const manual = (tab: TourDestination["tab"]): TourDestination => ({ view: "studio", mode: "manual", tab });
const shorts = { view: "studio", mode: "shorts" } as const;
const history = { view: "history" } as const;

export const TOUR_STEPS: readonly TourStep[] = [
  { id: "welcome", chapter: "Welcome", title: "Find your way around Remix Studio",
    description: "Follow the highlights to learn the editing options. You can explore the whole tour or jump straight to a topic.",
    options: [["Import → edit → export", "Bring a video, choose how to edit it, then review your finished cut."],
      ["Go at your own pace", "Use Next, Back or Jump to topic. No video is needed to follow along."],
      ["Leave whenever you like", "Skip, ×, Escape or a click outside closes the tour. Open Quick guide to replay it."]],
  },
  { id: "imports", chapter: "Your footage", title: "Bring in your videos", target: ".import-panel .dropzone", destination: auto,
    description: "Every imported video joins the same workspace for Auto, Manual and Short clips.",
    options: [["Browse or drop files", "Import one video or a batch. The uploader shows your current file and batch limits."],
      ["Pause and resume", "Large files upload in chunks. After reloading, select the same unchanged file to resume."],
      ["Import status", "Follow upload and preparation progress. Cancel unfinished imports or dismiss completed cards."]],
  },
  { id: "links", chapter: "Your footage", title: "Import several video links at once", target: ".import-social", destination: auto,
    description: "Use Import from a video URL instead of uploading a file. Paste a YouTube video, Shorts or youtu.be share link; TikTok and Instagram links work too. Import one URL or a batch separated by new lines, spaces or commas.",
    options: [["Check your batch", "The button shows how many videos will import. Duplicates are skipped; invalid entries stay in the field for correction while valid links can continue."],
      ["Download in the background", "Each video has its own progress with your other imports. Downloads continue while the app server is running."],
      ["If a link cannot download", "Use Retry import on the failed card to request a fresh download without pasting the URL again. Rate limits may need a short wait; private or restricted videos may need a local copy through Browse files."]],
  },
  { id: "local-files", chapter: "Your footage", title: "Use large originals without copying", target: ".import-link-button", destination: auto,
    description: "Link files on this computer lets you paste full paths to videos stored on the machine running the app.",
    options: [["One path per line", "On Mac, select files in Finder and press Option + Command + C to copy their paths."],
      ["Keep originals in place", "Linked files must stay at the same path and remain unchanged until your exports finish."]],
  },
  { id: "modes", chapter: "Editing modes", title: "Choose how you want to edit", target: ".mode-switch", destination: auto,
    description: "Switch modes at the top of the workspace. Each gives you a different amount of control.",
    options: [["Auto remix", "Choose your preferences; Auto selects an excerpt and prepares the edit."],
      ["Manual", "Set the trim, picture, audio and text yourself. Manual settings stay separate from Auto."],
      ["Short clips", "Build named shorts from exact timestamps, including multiple sequences from a long recording."]],
  },
  { id: "auto-scope", chapter: "Auto", title: "Choose which video you are changing", target: ".auto-scope", destination: auto,
    description: "Select a source card or use Editing preferences for to change that video's Auto settings.",
    options: [["Per-video preferences", "Format, length, text, sound, visuals and version count belong to the selected source."],
      ["Use for all videos", "With multiple sources, copy these preferences to the other videos and future imports."],
      ["Starting preferences", "Before importing, your choices become the defaults for new videos."]],
  },
  { id: "black-bands", chapter: "Auto", title: "Frame your video with black bands", target: ".auto-layout", destination: auto,
    description: "Choose the output Format, then enable Black bands to make room for persistent captions above and below your picture.",
    options: [["Format and fit", "Choose portrait, square, 4:5, landscape or original. Keep the whole picture preserves the source; Fill the window crops its edges."],
      ["Top and bottom bands", "Adjust their heights separately. A portrait source stays fully visible with side space when you keep the whole picture."],
      ["Band text", "Write a headline above and an optional caption below. Adjust text size; the white text wraps and shrinks to fit."]],
  },
  { id: "footage-presets", chapter: "Auto", title: "Place your own footage precisely", target: ".auto-panel .own-footage", destination: auto,
    description: "Add my own footage places an uploaded clip exactly where you want it, independently of automatic B-roll matching.",
    options: [["Insert or cover", "Insert adds time to the edit. Cover replaces the picture while the original speech continues."],
      ["Choose the timing", "Position is measured in the edit; clip start and end select part of the uploaded footage. Add whole clip at end follows the end automatically."],
      ["Sound and framing", "For inserted footage, keep its audio or mute it. Fit the whole clip or crop it to fill the frame; remove a placement to leave it out."]],
  },
  { id: "auto-presets", chapter: "Auto", title: "Save an Auto finishing preset", target: ".auto-panel .finishing-presets", destination: auto,
    description: "Name your current finish, save it in this browser, then choose it and apply it to another video's Auto settings.",
    options: [["What is saved", "Format, pacing, captions, sound and supporting-visual preferences. Length, version count, narration and selected library clips stay with each video."],
      ["Separate presets for each mode", "Auto, Manual and Short clips each have their own presets. Applying band styling keeps the video's written band text."],
      ["Manage your presets", "Choose a saved preset to apply or delete it. Saving a preset does not start an export."]],
  },
  { id: "pacing", chapter: "Auto", title: "Set the rhythm of the conversation", target: ".auto-panel .pacing-options", destination: auto,
    description: "Pacing decides how much space to keep between spoken phrases.",
    options: [["Original / Natural / Tight", "Keep pauses as recorded, preserve breathing room, or shorten longer pauses."],
      ["Custom", "Set the pause threshold and how much silence to retain."],
      ["Remove isolated fillers", "Optionally remove clear, separately timed “um” and “uh” sounds while keeping meaningful words."]],
  },
  { id: "length-versions", chapter: "Auto", title: "Set length and number of versions", target: '[data-tour="auto-length"]', destination: auto,
    description: "Output preferences controls how much of the source Auto uses and how many different edits it tries to make.",
    options: [["Target length", "Enter a whole number of seconds. It is an upper limit; Auto never extends footage to reach it."],
      ["Maximum versions", "Request 1–10 versions per video. Similar cuts can be skipped, so the finished count may be lower."],
      ["Generate anyway", "A skipped version can be explicitly generated from its export card."]],
  },
  { id: "captions", chapter: "Auto", title: "Choose how speech captions are added", target: '[data-tour="auto-captions"]', destination: auto,
    description: "Speech captions follow spoken words. They are separate from the persistent words in your black bands.",
    options: [["Auto · avoid duplicates", "Check for captions already baked into the footage before adding new text."],
      ["Keep original / Add new", "Keep original adds no speech captions, hooks or callouts. Add new explicitly requests generated captions."],
      ["Caption appearance", "Choose a look, then adjust font, size, color, case, outline, shadow, spacing, alignment, position and background. Leave lower band text empty if captions use that space."]],
  },
  { id: "sound", chapter: "Auto", title: "Keep or reshape the original sound", target: '[data-tour="auto-sound"]', destination: auto,
    description: "Sound controls audio treatment. New narration is a separate choice below the review settings.",
    options: [["None · keep original audio", "Skip sound effects, loudness normalization, cut fades and replacement narration. Audio still follows the video cuts and is re-encoded for export."],
      ["Auto or a sound look", "Auto measures speech and chooses a treatment. Or select Clear voice, Podcast, Warm, Bright, Noisy room, Smooth or Phone call yourself."],
      ["New narration", "When available, replace the voice with a scripted read. None and Keep original captions prevent replacement narration."]],
  },
  { id: "reviews", chapter: "Auto", title: "Choose the automatic review checks", target: '[data-tour="auto-review"]', destination: auto,
    description: "Reviews help find issues with the selected story and the finished video.",
    options: [["Editorial review", "Check the opening, meaning and ending. Choose Check and repair, Check only or Off."],
      ["Review finished picture & sound", "Inspect sampled frames and captions against the soundtrack. This adds processing time."],
      ["Review the findings yourself", "AI checks can miss things. Where enabled, DeepSeek receives the relevant text or sampled images; transcription stays local."]],
  },
  { id: "supporting-visuals", chapter: "Auto", title: "Choose optional supporting visuals", target: ".supporting-visuals", destination: auto,
    description: "Choose any combination, or leave every source off to keep only your original footage.",
    options: [["Pixabay / Pexels", "Add moving stock footage. HyperFrames / Remotion add illustrated explainer cards. My B-roll uses clips from your own library."],
      ["Count, coverage and stock style", "Set the total shot count and maximum percentage of the result they may cover. The animation-only stock filter uses Pixabay."],
      ["Matching and library", "Upload, tag and select library clips; choose tags or AI matching. Stock matching and illustrated explainers need configured DeepSeek access. Unsuitable shots can be skipped; read the export's unfilled requests."]],
  },
  { id: "auto-render", chapter: "Auto", title: "Choose what to render", target: ".auto-render-bar", destination: auto,
    description: "The render bar summarizes the result you are asking for before you start.",
    options: [["This / selected / all videos", "Choose one source, check source cards for a selection, or process the whole workspace."],
      ["Auto remix", "Start the batch when you are ready. Each source uses its own saved preferences."],
      ["Follow Exports", "Watch progress and review the finished versions there. This tour never starts a render."]],
  },
  { id: "manual-frame", chapter: "Manual", title: "Take control of the picture", target: '[data-tour="manual-frame-it-right"]', destination: manual("essentials"),
    description: "Essentials contains Color looks, Frame it right, and Pace & sound. Tabs separate the controls; All controls shows them together.",
    options: [["Frame it right", "Set format and resolution, fill and crop, fit the whole video, or use a blurred background. Black bands and their text are available here too."],
      ["Subject and motion", "Adjust zoom, horizontal or vertical position, mirror, gentle push-in and video cleanup."],
      ["Preview", "Compare the original with your draft. Render a five-second preview to check effects that the live preview only approximates."]],
  },
  { id: "manual-audio", chapter: "Manual", title: "Fine-tune speed and audio", target: '[data-tour="manual-pace-sound"]', destination: manual("essentials"),
    description: "Use the Pace & sound controls to make deliberate changes to the selected video's soundtrack.",
    options: [["Speed, volume and mute", "Change playback speed or volume, or remove sound from the output."],
      ["Loudness and sound looks", "Normalization changes loudness. Sound looks change tone, noise and dynamics; switching looks leaves volume and normalization as set."],
      ["Replacement audio", "Upload another audio track or remove it to return to source audio. Mute takes priority over the track."]],
  },
  { id: "manual-sound-modifiers", chapter: "Manual", title: "Adjust individual sound effects", target: ".sound-looks .manual-subsection", destination: manual("essentials"),
    description: "Open Sound modifiers to fine-tune a sound look. Render a sample to hear these effects; the live preview does not include them.",
    options: [["Noise and tone", "Noise reduction tackles steady background noise; Low cut removes rumble. Bass, Presence and Treble reshape the tone."],
      ["Dynamics and fades", "Even out level reduces loud/quiet differences. De-ess softens sharp consonants. Fade in and Fade out soften the start and end."],
      ["Keep the original treatment", "Use the Original sound look, leave normalization off and fades at zero, and keep volume at 100% with no replacement track. Speed and cuts still affect the soundtrack."]],
  },
  { id: "manual-color", chapter: "Manual", title: "Adjust color and texture", target: '[data-tour="manual-light-color"]', destination: manual("color"),
    description: "Color & feel gives you individual picture adjustments, alongside the ready-made Color looks in Essentials.",
    options: [["Light & color", "Adjust brightness, contrast, saturation, temperature, hue shift and gamma."],
      ["Texture", "Control sharpness and film grain. Reset color adjustments if you want to start over."],
      ["Small changes are easy to compare", "Use the original/draft preview switch to judge the result before exporting."]],
  },
  { id: "manual-timing", chapter: "Manual", title: "Choose the timing and opening hook", target: '[data-tour="manual-trim-motion"]', destination: manual("advanced"),
    description: "Advanced contains Trim & motion, Give it a hook, Captions, and Export details.",
    options: [["Trim & motion", "Set start and end, shift the chosen interval, or tune blend and frame blend. Existing multi-cut edits retain their sequences."],
      ["Give it a hook", "Write opening text and set how long it appears."],
      ["Blend and frame blend", "Blend mixes in the preceding frame for a motion trail; Frame blend smooths across neighboring frames. Render a sample to judge the effect."]],
  },
  { id: "manual-captions", chapter: "Manual", title: "Add and style Manual captions", target: '[data-tour="manual-captions"]', destination: manual("advanced"),
    description: "Captions follow speech; opening hooks and black-band text are separate overlays.",
    options: [["Original captions / import SRT", "Keep existing text or upload a subtitle file. SRT timestamps must match the finished edit, including its cuts and speed."],
      ["Automatic captions", "Avoid duplicates keeps existing captions, including when detection is uncertain. Add new requests another caption layer. Local speech recognition follows the finished soundtrack, including added footage."],
      ["Appearance and preview", "Choose a look and adjust font, size, color, case, outline, shadow, spacing, alignment, position and background. Automatic captions are generated on export, not in the quick preview."]],
  },
  { id: "manual-footage-presets", chapter: "Manual", title: "Add footage and reuse your finish", target: ".manual-workflow-tools", destination: manual("essentials"), reveal: ".manual-workflow-tools .own-footage, .manual-workflow-tools .finishing-presets",
    description: "These tools sit below Supporting visuals in every Manual tab.",
    options: [["Add my own footage", "Insert adds duration; Cover changes the picture while speech continues. Set the edit position and clip in/out times, or append the whole clip. Choose inserted audio and fit/crop."],
      ["Finishing presets", "Save a named Manual finish in this browser, then choose and apply it to another video. Framing, color, audio, captions and visual preferences are reused."],
      ["What stays with the video", "Presets keep the video's cuts, speed, written text and uploaded media. Apply settings to all videos is a separate, broader action."]],
  },
  { id: "manual-prompt", chapter: "Manual", title: "Describe an edit and review the proposal", target: ".manual-workflow-tools .prompt-editor", fallbackTarget: ".manual-workflow-tools", destination: manual("essentials"),
    description: "After selecting a video, Describe your edit can prepare changes to color, speed, audio, framing, trim and titles using DeepSeek.",
    options: [["Ask for specific changes", "Write your request or choose an example. Review the proposed changes and any request for clarification."],
      ["Apply or discard", "Apply changes updates this video's settings; it does not render. Discard leaves them as they were."],
      ["Undo last prompt", "Undo is available while those applied settings are still unchanged. Later manual edits can make that undo unavailable."]],
  },
  { id: "manual-visuals", chapter: "Manual", title: "Add B-roll to your manual edit", target: ".manual-supporting-visuals", destination: manual("essentials"),
    description: "Supporting visuals sit below the editing controls in every Manual tab. Your cuts, speed and audio settings remain yours.",
    options: [["Choose sources", "Mix Pixabay, Pexels, HyperFrames, Remotion and My B-roll, or leave all off for original footage."],
      ["Count, coverage and matching", "Set how many supporting shots to request and how much footage they may cover. Select uploaded clips and match by tags or available AI."],
      ["Check the export", "Supporting shots are assembled during the full export; Live and five-second previews show your manual footage without them."]],
  },
  { id: "manual-finish", chapter: "Manual", title: "Save your finish and render a batch", target: '[data-tour="manual-export-details"]', destination: manual("all"),
    description: "Set the output details, then use the render bar below the workspace to export.",
    options: [["Export details", "Choose source, 24, 30 or 60 fps and whether to clean file metadata."],
      ["Batch controls", "Choose 1–5 versions per video, enable subtle variations if wanted, and choose the render scope. Each video uses its own settings unless you apply settings to all."],
      ["Start over or experiment", "Reset settings and Surprise me are in the workspace toolbar. Color looks change color only; they leave framing, timing and sound alone."]],
  },
  { id: "shorts-discovery", chapter: "Short clips", title: "Find moments in a long recording", target: ".shorts-discovery", destination: shorts,
    description: "Find my best clips suggests complete ideas from the selected source. You can also skip discovery and create shorts yourself.",
    options: [["Describe what to find", "Optionally enter a brief, choose a maximum of 1–20 clips, and set minimum/maximum seconds. Speech recognition runs locally; selection uses DeepSeek."],
      ["Review the suggestions", "Play excerpts and inspect Speech & surrounding context. Check whether all speech sections were reviewed or only part of the recording."],
      ["Keep your favorites", "Keep clip or Keep all visible creates editable drafts. Dismiss unwanted ideas or Find other moments. Nothing renders until you approve and render drafts."]],
  },
  { id: "shorts-source", chapter: "Short clips", title: "Navigate the original recording", target: ".shorts-player", destination: shorts,
    description: "Source preview uses timestamps from the original recording, even when your short combines several separate moments.",
    options: [["Seek precisely", "Use playback, the scrubber or Source timestamp. Enter seconds or HH:MM:SS.mmm and use Go to time."],
      ["Source sample", "Render sample at this time makes a five-second sample, up to 720p. It also helps when the browser cannot play the original format."],
      ["Source versus finished short", "This sample checks the original moment. Preview this short, in the editor, checks the edited framing and finish."]],
  },
  { id: "shorts-transcript", chapter: "Short clips", title: "Build a short from its transcript", target: ".shorts-transcript", fallbackTarget: ".shorts-player", destination: shorts,
    description: "Edit with the transcript sits under the source preview. Transcribe the video once on your computer, then choose moments by their words.",
    options: [["Select speech", "Click a word to jump there. Drag across words or Shift-click to select. Find words searches long recordings."],
      ["Shape the short", "Add the selection as a new sequence, remove words from the selected short, or start a new short from it. Undo transcript edit reverses each change."],
      ["Listen before rendering", "Play selection plays exactly that range. Recognition can mishear words; words with a dotted underline have low confidence."]],
  },
  { id: "shorts", chapter: "Short clips", title: "Build a short from exact sequences", target: ".shorts-editor", destination: shorts,
    description: "Click New short or select a kept draft to reveal the editing controls. Give each short a name.",
    options: [["Choose source in/out times", "Type each sequence's start/end, or set them from the source playhead. Add another sequence at the playhead to combine moments."],
      ["Arrange your story", "Move sequences up/down, remove one, or go to its start to check it. Duplicate short makes another draft to try a different edit."],
      ["Saved in this browser", "Drafts are stored locally. If a source is missing, reimport and reconnect it; the saved sequences remain. Download finished exports separately."]],
  },
  { id: "shorts-frame", chapter: "Short clips", title: "Choose the short's layout and quality", target: ".shorts-output-settings", fallbackTarget: ".shorts-editor", destination: shorts,
    description: "With a draft selected, open Frame & quality to control how the source becomes a short.",
    options: [["Format, quality and fit", "Choose portrait, square, 4:5, landscape or original, then source quality, 720p or 1080p. Single-view layouts support crop, blurred background or fitting the whole picture."],
      ["Conversation or presentation", "Split stacks two people with separate position controls. Presentation puts the full scene above a speaker close-up. Check both regions in a preview."],
      ["Manual crop", "Drag the orange frame or use Crop zoom and subject position. Position applies across the sequences; zoom in to make room to move along a fully visible dimension."]],
  },
  { id: "shorts-tracking", chapter: "Short clips", title: "Follow a face or the active speaker", target: ".shorts-focus-card", fallbackTarget: ".shorts-editor", destination: shorts, reveal: ".shorts-output-settings",
    description: "Auto center speaker appears for a single-view crop layout. Tracking runs on your computer.",
    options: [["Choose the tracking method", "Follow selected face tracks the face nearest your starting crop. Follow active speaker also uses speech and face motion to decide who is talking."],
      ["Check the result", "Read the status, preview the movement and retry if needed. Where tracking fails or finds no face, the manual position is used."],
      ["Return to a fixed crop", "Turn automatic centering off, drag the frame or change its position. Manual positioning switches tracking off."]],
  },
  { id: "shorts-pacing", chapter: "Short clips", title: "Review pacing changes before applying", target: ".short-pacing", fallbackTarget: ".shorts-editor", destination: shorts,
    description: "Refine the pacing opens for a draft with its source available. Analysis runs locally and proposes trims for you to review.",
    options: [["Choose the rhythm", "Original keeps pauses; Natural or Tight shortens them. Custom lets you set the threshold and retained silence. Isolated filler removal is optional."],
      ["Listen and choose", "Review suggested trims, listen around each one and uncheck any you want to keep. Apply selected trims updates the sequences."],
      ["Undo or recheck", "Undo pacing changes restores the earlier sequences. After changing sequences or pacing settings, review fresh suggestions before applying."]],
  },
  { id: "shorts-finish", chapter: "Short clips", title: "Finish and preview your short", target: ".shorts-editor .finishing-presets", fallbackTarget: ".shorts-editor", destination: shorts, reveal: ".shorts-editor .own-footage",
    description: "Once a draft is selected, add footage, reuse a finish and check a sample before the full render.",
    options: [["Your footage and presets", "Insert or cover with your uploaded clips. Short clips presets reuse format, layout, tracking and cleanup while retaining each short's timestamps and subject positions; apply to this or selected shorts."],
      ["Audio and cleanup", "In Frame & quality, Even out audio normalizes the sequences. Gentle cleanup reduces picture noise and sharpens lightly; it cannot restore missing detail."],
      ["Preview this short", "Render a five-second sample of the edit. Check the duration and any timestamp errors before approving the draft."]],
  },
  { id: "shorts-review", chapter: "Short clips", title: "Review and approve the draft queue", target: ".shorts-collection", destination: shorts,
    description: "Your short clips holds the saved drafts. Select a draft to edit it, or select several for batch approval.",
    options: [["Review the outline", "Write a Summary and optional Added contribution, inspect source timestamps and preview sequences. These notes do not add text or narration to the video."],
      ["Check previous uses", "Previous exports & publications reports source overlap from this workspace's history. Refresh history when needed; outside posts are unknown."],
      ["Approve or revise", "Approve individual or selected drafts, filter Needs review/Approved, revoke approval or delete a draft. Changing a draft requires approval again."]],
  },
  { id: "shorts-render", chapter: "Short clips", title: "Render the shorts you approved", target: ".shorts-render-bar", destination: shorts,
    description: "Choose the scope at the bottom of Your short clips, then start the batch when you are ready.",
    options: [["All approved / this / selected / all", "Every draft in the chosen scope must be approved. If the button is disabled, resolve errors and approve those drafts or choose All approved drafts."],
      ["Watch progress in Exports", "Review the finished videos and any flagged moments, make revisions if needed, then download."],
      ["Keep the source available", "Drafts alone are not video files. Their sources and uploaded footage must still be available for rendering."]],
  },
  { id: "exports", chapter: "Results", title: "Review and download your exports", target: ".exports-panel", destination: { view: "exports" },
    description: "Exports groups your jobs into batches, with current stages, warnings, errors and completed videos.",
    options: [["Progress and recovery", "Cancel work, retry eligible failures, or read why a version was skipped."],
      ["Preview and download", "Watch the result and read what changed. Download an MP4, available SRT captions, or the completed batch as a ZIP."],
      ["Keep what you need", "Generated files are retained for the period shown in the app. Download them before cleanup; History keeps the editing record."]],
  },
  { id: "revisions", chapter: "Results", title: "Refine a finished result", target: ".exports-panel", destination: { view: "exports" },
    description: "Open Edit this result on an editable export to make a revision without starting the whole edit again.",
    options: [["Cuts, visuals and text", "Refine sequences, replace supporting shots, adjust hooks and captions, and change framing or black-band text."],
      ["Placement guides", "Use the platform interface guide to keep important text away from social-app buttons and post descriptions."],
      ["Review and render", "Inspect flagged moments, retry available reviews, preview changes and render a new revision. These controls appear when an editable result exists."]],
  },
  { id: "history", chapter: "History", title: "Find earlier exports and source uses", target: ".history-toolbar", destination: history,
    description: "History keeps the editing record, including revisions, even after the generated video expires.",
    options: [["Search, refresh and pages", "Search by title or source name, refresh the list, and use Previous/Next to browse older exports."],
      ["Source matches", "Open history from a source card to see earlier exports and possible picture matches. Similarity is a visual hint to check, not an export block. Show all history clears that source filter."],
      ["Files versus records", "Preview or download MP4 while the file is available. After expiry, the saved record and any retained preview frame remain; the video cannot be downloaded from that record."]],
  },
  { id: "history-details", chapter: "History", title: "Inspect how an export was made", target: ".history-card .history-settings", fallbackTarget: ".history-panel", destination: history, reveal: ".history-card:first-child .history-excerpts",
    description: "Once an export is recorded, expand its details to understand the source material, settings and review findings.",
    options: [["Source excerpts & stock footage", "Inspect original intervals, available source text and stock shots, including reuse across the listed exports."],
      ["Settings used for this export", "Read the saved configuration, actual visual coverage, captions and narration. Older exports may have no retained settings."],
      ["Automatic reviews", "Read the editorial and finished-picture/sound reports. When the file is still available, preview flagged moments or retry an available finished review."]],
  },
  { id: "history-publications", chapter: "History", title: "Record where you published a video", target: ".history-card .history-card-actions", fallbackTarget: ".history-panel", destination: history,
    description: "On an export card, Record publication logs a post you already published yourself.",
    options: [["Publication details", "Choose TikTok, Instagram or YouTube, enter the account/channel and publication date/time, and optionally add the post link."],
      ["Multiple posts", "Record each publication separately. Edit record corrects details; removing a record only removes it from this history."],
      ["A record, not a posting tool", "Saving changes the history status to Published. It does not upload, edit or delete posts on the social platform."]],
  },
  { id: "history-review", chapter: "History", title: "Record your review and observed results", target: ".history-card .history-measurements", fallbackTarget: ".history-panel", destination: history,
    description: "Open Record review & results on an export card. Leave unknown measurements blank.",
    options: [["Your editorial verdict", "Choose accepted unchanged, accepted after correction or rejected. Record issues, opening/ending quality, B-roll reviewed/accepted, caption corrections, correction time and notes."],
      ["Compare like with like", "Use the same benchmark case for comparable footage, and an approach name for the editing idea."],
      ["Platform observations", "Add dated results for a platform or recorded post: views, watch time, completion, saves and shares. Log reach assessments and feedback; confirmed restrictions require a platform notice. Results are entered by you, not fetched automatically."]],
  },
  { id: "history-comparison", chapter: "History", title: "Compare settings and measured outcomes", target: '[data-tour="history-comparison"]', destination: history, reveal: '[data-tour="history-settings-outcomes"]',
    description: "Use the two comparison panels above the export cards to learn from saved reviews and observations.",
    options: [["Settings & posting outcomes", "Compare the listed page's posts by settings profile and platform. Similar outcomes do not prove that a setting caused them."],
      ["Compare recorded results", "Compare all recorded reviews by approach and benchmark case. Acceptance rates use explicit human verdicts; undecided exports and automatic repairs are reported separately."],
      ["Download measurements", "Export all measurements as CSV or JSON. The latest platform results for listed exports use one latest snapshot per recorded post; compare similar observation periods."]],
  },
  { id: "ready", chapter: "Ready", title: "Your next cut starts here", target: ".mode-switch", destination: auto,
    description: "Import a video, choose a mode, then review your settings before rendering.",
    options: [["Come back whenever you need", "Quick guide and How it works reopen this tour. Jump to topic goes straight to a particular option."],
      ["Your work stays yours", "The tour only moves between views. Your settings, footage and exports are unchanged."],
      ["Once per session", "This guide opens automatically once per browser-tab session. Reloading after you finish or dismiss it keeps it closed."]],
  },
];
